DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE AUTHORITIES CASCADE CONSTRAINTS;

CREATE TABLE USERS (
    USERNAME NVARCHAR2(128) PRIMARY KEY,
    PASSWORD NVARCHAR2(128) NOT NULL,
    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL --no boolean in oracle
);


CREATE TABLE AUTHORITIES (
	ID NUMBER(10) PRIMARY KEY,
    USERNAME NVARCHAR2(128) NOT NULL,
    AUTHORITY NVARCHAR2(128) NOT NULL
);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ENABLE;



INSERT INTO USERS (username, password, enabled) VALUES ('user1','$2a$10$yl7N17Pooyc/HSy7t1rsYe4I2BVQnv8.woLrYeBPL.JnfXMCXBCve', 'Y');
INSERT INTO USERS (username, password, enabled)  VALUES ('admin1','$2a$10$j1K7Yx1ZqbZMYPgUArjxR.z6qYhfRmQ94rh0J8GZZRsEtGYYQSicq', 'Y');

INSERT INTO USERS (username, password, enabled)  VALUES ('user2','$2a$10$CxkZoFkQAHplkwGFwbJ/Z.0P7mNsoHV1yVArCj38afUpUHULQct1K', 'Y');
INSERT INTO USERS (username, password, enabled)  VALUES ('admin2','$2a$10$lZf31UbPjtUKcHeK6VsRauLjkIrVb7ZhlHkm5IeFBsLQ2QSwp41RW', 'Y');

INSERT INTO AUTHORITIES (id,username, authority) VALUES (1,'admin1','ROLE_ADMIN');
INSERT INTO AUTHORITIES (id,username, authority) VALUES (2,'admin2','ROLE_ADMIN');
INSERT INTO AUTHORITIES (id,username, authority) VALUES (3,'user1','ROLE_USER');
INSERT INTO AUTHORITIES (id,username, authority) VALUES (4,'user2','ROLE_USER');
