package com.inetum.appliBibliotheque.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Embeddable
@Getter @Setter @NoArgsConstructor @EqualsAndHashCode
public class EmpruntCompositePk implements Serializable {
	private static final long serialVersionUID = 1L;
	private Long idLivre;
	private Long idLecteur;

	public EmpruntCompositePk(Long idLivre, Long idLecteur) {
		super();
		this.idLivre = idLivre;
		this.idLecteur = idLecteur;
	}

	@Override
	public String toString() {
		return "EmpruntCompositePk [idLivre=" + idLivre + ", idLecteur=" + idLecteur + "]";
	}
	
	
//+get/set , equals et hashcode (generated by eclipse)
	
	
}